### ISSUE TITLE
Create a .TODO or feature roadmap?

### ISSUE THREAD

**Issue by thomastu** [ellmetha/django-machina#1]
This project looks like it has a lot of potential, but project management and roadmap seems a bit nebulous.  Would be nice to see a todo or feature roadmap leading to when you see this as being fit for a production environment to make it easier to make code contributions.

**Comment by ellmetha** [comment]
Hi,

Thanks for your comment.
I will add a "TODO" section in the README file. But here's an overview of current key tasks:

* Documenting the customization features provided by *django-machina* and some common use cases
* Implementing the topic subscription feature : a user can get a list of all topics to which he subscribed

I also need to find some "beta testers" who could try to use *django-machina* into their own projects in order to get some feedbacks ;)

**Comment by thomastu** [comment]
For something that supposedly isn't fit for a production environment yet, this is very well polished : )

With regards to the documentation issue, do you mean being able to override the default machina templates or extending them with your own project templates?  If so, I could come up with some documentation for how to do that.

**Comment by ellmetha** [comment]
Well, the README indicates that project is not "production-ready" because it has never been heavily used in production for now (and I still need to get some feedbacks about the use of this module). So it should not be considered as "production-ready". :)

I will try to get new testers soon. After some testing I should release an alpha version of the module.

As regards documenting the customization features of *django-machina*, I mean:

* being able to override *django-machina* models
* being able to override forum views, forms (or any other class)
* being able to override forum templates

*django-machina* relies on a dynamic class loading system that allows to override or extend CBV, forms or even models. These mechanisms are similar to the ones used by the [django-oscar](https://github.com/django-oscar/django-oscar) e-commerce framework (more information [here](http://django-oscar.readthedocs.org/en/releases-1.1/topics/customisation.html) and [here](http://django-oscar.readthedocs.org/en/releases-1.1/topics/class_loading_explained.html)). These topics need to be documented.
