### ISSUE TITLE
How do the see/read permissions work?

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#138]
As I understand from [the documentation](https://django-machina.readthedocs.io/en/stable/forum_permissions.html) granting someone permission to *see* a forum enables him to see the forum name listed, granting permission to *read* the forum also gives permission to see (and read) the content (the topics).

However, I have the following structure:

```
Category
   Forum 1
       Topic A
       Subforum 1.1
           Topic B
   Forum 2
        Topic C
```

Now I have a group that I want to be able to read the content of Subforum 1.1 and it's Topic B, but not the content of Forum 1 (so not Topic A). Forum 2 is free to seeing and reading.
So I granted the permission to see on Forum 1 and see + read on Subforum 1.1. There's see and read permission on the Category and also on Forum 2.

The result is that this group can only see and read Forum 2. While I expected it to be able to also see the name of Forum 1 and the name and content of Subforum 1.1.

There are no global rights set for this group.

**What am I missing??**

(Also it looks like 'read' does not overrule 'see'. If you grant read but not see permission, you still can't see (and thus read) the forum. So 'read' always needs 'see' permission to work.)

**Comment by ellmetha** [comment]
Hello @BrendaH.
Sorry for the late response. What you're trying to do is impossible with django-machina. You must have access (read permission) to a parent forum in order to "traverse it" and access any of its subforums.
So you could either give "read" access to Forum 1 or move Subforum 1.1 outside of Forum 1 to achieve what you're trying to do.
