### ISSUE TITLE
Should I run makemessages on PR?

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#169]
I was wondering if I should run makemessages when I have edited code and added strings that need to be translated?
When I run it, I notice that all paths to the files in the resulting .po file have their slashes converted to backslashes. Probably a difference between Linux/Windows. This does not seem desirable to me since it makes the diff less readable.
Also, I am in no position to translate anything else than my own language, so if I do this... should I just do it for Dutch, or for all languages?

Another side effect is that in the `example project/main/templates` dir I am left with some extra `.html.py` files with just garble in them where the normal template has html/code.

So what's the way to go on this? Submit the PR code without translations?

**Comment by ellmetha** [comment]
Hey @BrendaH 

No need to run `makemessages` for you PR branches. If one of your PR is merged I'll run it myself and ensure that the translation keys are pushed to [Transifex](https://www.transifex.com/django-machina-team/django-machina/) so that you can provide translations in your language from there. 😉
