### ISSUE TITLE
Forum member avatar not loading

### ISSUE THREAD

**Issue by mmeinzer** [ellmetha/django-machina#17]
The GET request for the avatar is returning a 404 error: `Not Found: /forum/member/profile/1/machina/avatar_images/homer_2SUQZII.png
[22/Mar/2016 02:23:38] "GET /forum/member/profile/1/machina/avatar_images/homer_2SUQZII.png HTTP/1.1" 404 5471`

The file is located in mysite/machina/avatar_images and I have not changed the default location for avatar image storage.

**Comment by ellmetha** [comment]
Hi!
Does this error appear on topic pages?
It could  to be related to an incorrect configuration of your ``MEDIA_ROOT`` or ``MEDIA_URL`` settings. Indeed the path to the image should be something like ``/media/machina/avatar_images/homer_2SUQZII.png`` instead of ``/forum/member/profile/1/machina/avatar_images/homer_2SUQZII.png``. Have you configured your project to serve media files in DEBUG mode?

**Comment by mmeinzer** [comment]
I haven't configured MEDIA_ROOT or MEDIA_URL. I will go ahead and do that. Thank you

**Comment by nkgilley** [comment]
@mmeinzer How did you get this fixed?  I have defined a MEDIA_ROOT but I still get the problem.

**Comment by mmeinzer** [comment]
Unfortunately I haven't used django-machina in over a year. I'm not running
any sites on it anymore. Sorry!
