### ISSUE TITLE
cannot import name 'urls' from 'machina'

### ISSUE THREAD

**Issue by y0d32** [ellmetha/django-machina#199]
Guys,

sorry to bother you. Just downloaded the archieve and after pip install -r requirements, while i runserver i got this error ==>ImportError: cannot import name 'urls' from 'machina' (/Users/user/mypython/lib/python3.7/site-packages/machina/__init__.py)
Am running it on a MAC.
 There are other additional instalations I have to do?

**Comment by raghavankit11** [comment]
I am also facing exactly same problem, 

  File "C:\django-projects\django-machina\example_project\project\urls.py", line 5, in <module>
    from machina import urls as machina_urls
**ImportError: cannot import name 'urls' from 'machina'** (C:\django-projects\django-machina\venv\lib\site-packages\machina\__init__.py)

I was wondering if someone has got a answer to this?

**Comment by raghavankit11** [comment]
Finally after spending couple of hours, I was able to diagnose the problem.

**Root Cause**
I forked the latest version of django-machina from this GIT repo, pycharm was correctly able to use the django-machina using the INSTALLED_APPS mentioned in base.py (samle_project/project/settings) and that is why it was able to start the server correctly. 

However, the makemigration was still referring machina from the list of installed modules (pip install), which was installed using the requirements.txt where its version  0.7.1 was mentioned along with Django 2.1, this combination was problematic because of url/path keywords.

 
**Solution**
I uninstalled django-machina using pip uninstall django-machina, and installed the latest version by removing the version in requirements.txt, which eventually installed the latest version of django-machina as a module as well. This removed the mismatch that was occurring due to the different django versions being used in old (0.7.1) version of django-machina and the latest django used in sample-project.

Please try above, I am sure it would solve your problem.

Let me know if you see some other error.
