### ISSUE TITLE
For my project, I re-wrote the permission-checker ... how can I submit it?

### ISSUE THREAD

**Issue by SundialServices** [ellmetha/django-machina#205]
For my project, I found that the existing `forum_permission.checker.get_perms_for_forum` routine was ... well ... _broken._  And that logic in `forum_permission.handler` largely duplicated the same problem.

So ... I _rewrote_ the checker-routine.  I then found that the handler could be greatly simplified by relying on the checker instead of duplicating its logic.  **(Files attached below.)**

Anyway, here's what I did:  `checker` now *searches* for the answer.  It works by accumulating a list of all of the permissions which were explicitly granted or explicitly denied, working outward from the most-specific case to the most-general. (While considering forums, it also working outward from the specified forum to any and all of its containers.)  In each case, the rune is that "the _first_ explicit grant/deny rule encountered always wins."  Thus, more-specific rules supersede all rules that are more general.

`DEFAULT_AUTHENTICATED_USER_FORUM_PERMISSIONS` is used only, "as a last resort," if the user is authenticated **and** the preceding search encounters nothing.  _(In retrospect,_ maybe it shouldn't decline to be considered if the list is non-empty ... your call.)

The routine is short – about 200 lines – and by relying on `get_perms` it also greatly simplifies and reduces the size of the `handler.`  I think it just might fix some long-standing bugs, too.

It _also_ has the useful feature that, if forums are nested, "default permissions" can conveniently be granted at the parent-forum level, such that they will cascade-down to all child-forums old or new.

_Hey, waitaminit, I can attach files to this post ... So, here they are._

Quite honestly, I think that this might clean up a lot of problems.  _(Fair warning: there will be some "comments" in there that you will want to remove – please don't take them personally.  I was fairly-frantic when I wrote them.)_ **:-)**

**P.S.:** _"Great_ forum!"

[checker.py.zip](https://github.com/ellmetha/django-machina/files/4554109/checker.py.zip)
[handler.py.zip](https://github.com/ellmetha/django-machina/files/4554113/handler.py.zip)

**Comment by BrendaH** [comment]
Thanks for taking the effort to share your code. Since the need for my forum project was diminished by the whole corona-thing I didn't see this post up till now...
The way to get your code into the project is to make a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) out of it:
Fork the project to your own account
Add a branch on your fork with the desired changes
Make a pull request to this repository

With the files you attached we do not know from which version of Machina you were working, so it makes it hard to compare stuff.
Did you check if all tests still run ok?

**Comment by ellmetha** [comment]
Hey @SundialServices, feel free to open a PR if you want to propose a new implementation of forum permissions handling! In the meantime, I am going to close this issue. 😉
