### ISSUE TITLE
Failed to import extended model

### ISSUE THREAD

**Issue by BoPeng** [ellmetha/django-machina#216]
Using the example from [the doc](https://django-machina.readthedocs.io/en/stable/customization/recipes/overriding_models.html),

when I extend `Topic` in `myapp.forum_conversation` in `myapp/forum_conversation/models.py` as follows:

```
from machina.apps.forum_conversation.abstract_models import AbstractTopic

# override Topic
class Topic(AbstractTopic):
    another_field = models.CharField(...)

from machina.apps.forum_conversation.models import *
```

Everythong appears to be working, `manage.py migrate` does add the new field. However,

```
from myapp.forum_conversation.models import Topic
```
will load `Topic` as `None`.

I am doing something hacky like

```
old_topic = Topic
from machina.apps.forum_conversation.models import *
Topic = old_topic
```
to get around the problem but I am wondering if I did something wrong here.

**Comment by BoPeng** [comment]
Could you also clarify how to extend/override urls, override forms and views? Do I need to do things like `from machina.apps.forum_conversation.forms import *`? I am reading the source code and trying to figure out things like `get_class` but your comments will surely help a lot. Thanks.

**Comment by ellmetha** [comment]
In order to override forms, views, urls, etc please refer to [Overriding an application](https://django-machina.readthedocs.io/en/stable/customization/overriding_applications.html) and [Customization underlying mechanisms](https://django-machina.readthedocs.io/en/stable/customization/underlying_mechanisms.html) in the documentation. These two sections should give you a good undersdtanding of how the module provides this override mechanism. But tl;dr: everything that can be overridden is imported dynamically using a `get_class` function, and if you need to import overridden classes later on, it's safer yo use `get_class` in your application too.

Regarding models, it's kindof the same story except that the "helper" method to import the model is `get_model` (it's not documented at the moment but it definitely should). If I take your example above, you could import your overridden model easily by doing:

```python
from machina.core.db.models import get_model
Topic = get_model('forum_conversation', 'Topic')
```

**Comment by BoPeng** [comment]
Many thanks. I somehow missed [Customization underlying mechanisms](https://django-machina.readthedocs.io/en/stable/customization/underlying_mechanisms.html) but I read the source code and figured out how to extend forms and views. It is indeed a pretty neat and powerful system.

Now I am trying to add my own URLs, and I failed again to find relevant information. :-)
