### ISSUE TITLE
Production Readiness

### ISSUE THREAD

**Issue by nsomaru** [ellmetha/django-machina#22]
As per this [installation note](https://django-machina.readthedocs.io/en/stable/getting_started.html#installation) in the docs, Machina is not considered "production ready." Why?

**Comment by ellmetha** [comment]
Hi!

The current release of *django-machina* (``0.3.0``) is classified as a *beta* release because I consider the project is still young to be considered mature. For example the ``0.3.0`` version of *django-machina* (which was released just few days ago) fixed a bug that prevented users to use non-latin characters when creating topics.

That said, the next release of *django-machina* will probably be a *stable* release. This does not prevent you to use *django-machina* though. :)

**Comment by nsomaru** [comment]
@ellmetha Hi and thanks for the feedback. Looking forward on integrating Machina into a project we have running; a stable release would be great, as well of some indications of what's blocking...

Thanks for what seems like a cool project :)
