### ISSUE TITLE
Resize or auto-thumbnail profile pictures

### ISSUE THREAD

**Issue by thomastu** [ellmetha/django-machina#3]
Image size issues with large images on profile photos.

![thumbnailissues](https://cloud.githubusercontent.com/assets/11164430/10770165/0a546ff4-7ca7-11e5-82cb-9cdcae122eee.png)

I think the desired behaviour is to either enforce a max-upload size, or to use something like sorl-thumbnail to display thumbnails in the default template.

**Comment by ellmetha** [comment]
Hi,
Images such

**Comment by ellmetha** [comment]
Hi,
Profile photos height and width dimensions can be configured using the following settings: ``FORUM_IMAGE_WIDTH`` and ``FORUM_IMAGE_HEIGHT``. If these settings are filled with appropriate values, the profile photos are resized during upload.

However the default value of these settings is ``None``.  I will update these settings in order to enforce a specific value by default (eg. width: 150px ; height: 250px).
