### ISSUE TITLE
CSS code is too broad

### ISSUE THREAD

**Issue by y2kbadbug** [ellmetha/django-machina#34]
This app does not integrate very well at all with base templates as setting major things like html, body, etc.

What is the best method to use to make this work better inside of an already existing site template?

**Comment by mikeshultz** [comment]
I was able to add something like this to machina's _base.html: 

    <body class=".forums">

Then just overrode whatever I needed with my own stylesheet specifically for machina.  But I agree with the premise here in that it integrates poorly and would be great to have some kind of prefix, maybe.

**Comment by ellmetha** [comment]
*django-machina*'s ``_base.html`` should not be used if you plan to integrate a forum into your existing application. This template is just here to allow users to rapidly get started with *django-machina*. But I agree: there should be a simple solution to change this base template.

I could introduce a new setting to override the "base" template that is extended from the machina's main ``board_base.html`` template in order to allow users to use their own base template (but of course this would come at the price to adapt the block names of the ``board_base.html`` template if necessary).

I also plan to add a new section to the documentation describing how to customize machina's templates.

**Comment by y2kbadbug** [comment]
@ellmetha, that would be great.  The biggest problem is your combiningg your CSS into a copy of the bootstrap CSS file.  These should be kept secret.  I already use Bootstrap for my entire site so it can cause some conflicts.  I was able to work around it a bit, but I was unable to get it to allow my sidebar without losing the ability to have the top information, such as the search bar, breadcrumbs, etc.

https://www.ircdriven.com/forum/ Is the example I am talking about.

Great software by the way!

**Comment by mikeshultz** [comment]
To be clear, I overrode `_base.html` with my own copy in my own app's source.  Though maybe I did it differently than was intended.  The documentation didn't have anything about that.

**Comment by y2kbadbug** [comment]
The biggest problem is it doesn't use {% block content %}.  It uses "body".  A standard Django base uses content for the block.  Plus when I tried to just wrap everything in content, it wouldn't show the forum_nav block.  If you could add the CSS stuff as template tags, one for bootstrap "if needed" and one for the separate forum specific styles.  I also use this [django-bootstrap3](https://github.com/dyve/django-bootstrap3) which you could add as a dependency.

**Comment by ellmetha** [comment]
Yep the main block name should be renamed, I agree. I'll also try to find a solution in order to properly separate the forum specific styles from the "vendor" styles. But I don't want to add django-bootstrap3 as a dependency of the project. ;-)

**Comment by y2kbadbug** [comment]
@ellmetha, I don't know if this is a related issue, but when using pagedown and my own modified base it does not parse the Markdown on the actual topic page, only on the post edit/update in the preview section.

**Comment by ellmetha** [comment]
Hmm, could you open another issue for this problem? When you do so, could you add the following information to your issue?

- the *django-machina* version
- the *django-machina* settings you have modified in your own settings

Thanks!

**Comment by y2kbadbug** [comment]
I see the commit but I wanted to ask if this also addressed the issue with how it uses the 'body' block AND the 'content' block which most templates just use 'content'.

**Comment by ellmetha** [comment]
> I see the commit but I wanted to ask if this also addressed the issue with how it uses the 'body' block AND the 'content' block which most templates just use 'content'.

No. Not yet :)

**Comment by ellmetha** [comment]
Just to be clear: *django-machina* already uses the ``content`` block pattern (see: https://github.com/ellmetha/django-machina/blob/707989c0f93b84b10cfe8e1bd23505e6f0857bf5/machina/templates/machina/board_base.html#L74). This means that all the machina's templates already wrap their contents into a ``{% block content %}{% endblock content %}``. In my point of view this is the desired pattern because all the templates associated with *django-machina*'s views use a "common" block name.

That said, the ``board_base`.html`` template (which extends the ``_base.html`` template) defines its contents inside a ``body`` block (which itself is defined inside the ``_base.html`` template). This is the ``board_base.html`` which defines the ``content`` block. It turns out that this ``board_base.html`` template also defines some other things (breadcrumb, messages, etc) before declaring the ``content`` block. This is precisely the common "block pattern" that is used in the vast majority of Django projects.

I can understand that this behaviour complicates things if you just wrap everything inside a ``content`` block. And you know that you can't define multiple ``{% block %}`` tags with the same name in the same template. So:

* you could override the ``board_base.html`` template in order to override its content and just wrap everything inside a ``content`` block. But you would have to override the inner ``{% block content %}{% endblock content %}`` declaration and rename the block: so you would have to adapt all the templates of *django-machina*
* you could add a ``body`` block inside your base template and update the ``board_base.html`` template so that it uses your base template
* ...

Anyway, I'll add a new section to the documentation describing how to customize these templates.

**Comment by y2kbadbug** [comment]
@ellmetha 

https://github.com/ellmetha/django-machina/blob/707989c0f93b84b10cfe8e1bd23505e6f0857bf5/machina/templates/machina/board_base.html#L12L77

It is using the "body" block so if your main template just uses the standard "content" block then you will not get the forum navigation or search bar.  I understand that I can modify the templates but when it comes to apps I try not to because the more templates I modify the more problems I can face if templates are changed in later releases.

All you get from the board_base.html is the stuff from other template files which include {% block content %}.  Losing the breadcrumbs, extra links and search are a big loss.

I have already modified mine so that everything is in content, however, I think it would be nicer if it was easier to integrate without heavy modifying any templates.

**Comment by ellmetha** [comment]
> It is using the "body" block so if your main template just uses the standard "content" block then you will not get the forum navigation or search bar.

In the vast majority of cases, users will want to override the navigation bar to use the navbar of their application. ;-) So it is not really a big deal.

> All you get from the board_base.html is the stuff from other template files which include {% block content %}. Losing the breadcrumbs, extra links and search are a big loss.

I don't agree with this. If you _really_ want to integrate the forum into your application you'll always have to override this template, no matter what it contains. Because the way the elements (breadcrumb, search bar, ...) are presented in this template needs to be adapted to your application layout & style.

What would you suggest? Using the ``content`` block instead of the ``body`` block in the ``_base.html`` and the ``board_base.html`` template? And modifying all the other templates that extend the ``board_base.html`` template? 'tis not an option for me.
