### ISSUE TITLE
Embedding images on a post

### ISSUE THREAD

**Issue by stianpr** [ellmetha/django-machina#42]
How did you envision users embedding images in a post? Currently one has to store the images externally and references them through a URL. But one can allow attachments and specifically images should be possible to be seen. Not needed to be downloaded.

**Comment by ginestra** [comment]
Hi,
Are you able to display images from a url? (Not working for us, the img url gets escaped).
Thanks

**Comment by stianpr** [comment]
> Hi,
> Are you able to display images from a url? (Not working for us, the img url gets escaped).
> Thanks

Hmm, you should report this as a separate issue with a detailed description on how the image URL is before and after escaped. This issue should not be addressing that bug.

**Comment by ginestra** [comment]
Hi,
I appreciate the answer.
Before reporting it as an issue I wanted to check whether is an issue on our end or if someone else had a similar problem.

**Comment by ellmetha** [comment]
@stianpr super sorry for the late answer. :wink: 

> How did you envision users embedding images in a post? Currently one has to store the images externally and references them through a URL. But one can allow attachments and specifically images should be possible to be seen. Not needed to be downloaded.

Currently all attachments are processed and displayed the same way. For sure we could allow attachments containing images to be properly displayed in the list of attachments, but this is not really necessary. Moreover this would require to use a tool to generate thumbnails in order to display image attachments in the list of attachments, and I don't think that this is a great idea to tie *django-machina* with a specific thumbnail library (*django-machina* is a generic module which does not make any assumption regarding the tools its users should use ; this does apply to thumbnail generation).

Regarding the problem of embedding images in post, I'd say that is not the responsibility of *django-machina* to handle image uploads. I'd say that this is the responsibility of the editor that is used to write posts. For example, if you were to use [django-ckeditor](https://github.com/django-ckeditor/django-ckeditor) for writing posts, you could use the functionalities provided by this module to handle image uploads. Perhaps a specific user has built his own solution to store files and images, perhaps another is using [django-filer](https://github.com/divio/django-filer)... The users should choose which solution is the best and how to integrate it with *django-machina*.

**Comment by SundialServices** [comment]
I know that `ckeditor` can do this (with the right plug-in), but when I try to do a drag-and-drop I get *"Incorrect Server Response."*  

It would benefit me _very_ greatly if you (or anyone) could provide an actual example of how this is correctly done in Machina.

**Comment by ellmetha** [comment]
Closing this (old) issue. @SundialServices you should refer to the ckeditor (and django-ckeditor?) documentation regarding your problem. 😉
