### ISSUE TITLE
Cannot use in Django 1.10.4

### ISSUE THREAD

**Issue by omret** [ellmetha/django-machina#43]
I follow the tutorial and cannot use machina.
I use :
  Django 1.10.4
  Python 3.5

The django debug page shows that `TemplateDoesNotExist at /forum/`.Then i found django 1.10 remove the TEMPLATE_DIRS from settings.py.I move config the path into TEMPLATES .But still cannot work. Does django1.10.4 cannot support machina?

**Comment by ellmetha** [comment]
It does. But the "getting started" section of the documentation should be updated in order to replace old settings (``TEMPLATE_DIRS``, ...) by the new ``TEMPLATE`` setting. Meanwhile you can have a look at the settings module of one of the example projects (eg. https://github.com/ellmetha/django-machina/blob/master/example_projects/demo/src/demo_project/settings/base.py#L97).
