### ISSUE TITLE
What is the purpose of `extra_css` block?

### ISSUE THREAD

**Issue by Toshakins** [ellmetha/django-machina#51]
I've found in the [`_base.html`](https://github.com/ellmetha/django-machina/blob/master/machina/templates/machina/_base.html#L24-L25) blocks called `extra_js` and `extra_css`.

Additionally, I've spotted that `js` block in [`board_base.html`](https://github.com/ellmetha/django-machina/blob/master/machina/templates/machina/board_base.html#L77-L87) is overriden.

As I thought, I can use `extra_css` block to apply styles specific to my website. However, then I've found the [`topic_create.html`](https://github.com/ellmetha/django-machina/blob/master/machina/templates/machina/forum_conversation/topic_create.html#L38-L40) where `extra_css` was overloaded.

My question: which block should be used for customization?

If it's a bug, won't you mind if I contribute? 🤓

**Comment by ellmetha** [comment]
Hi :wink: This is not really a bug. `extra_css` is used internally to apply new styles to specific pages (eg. pages containing forms). I wouldn't really recommend to use the machina's `_base.html` template. Why don't you use the base template of your own application?

The way I see it, I'd override `board_base.html` template by ensuring it can properly fit inside my own application's template and I'd ensure that it extends my own `base.html` template

`_base.html` and `board_base.html` template are just base templates allowing you to quickly get started with *django-machina*, but you're encouraged to override them in order to properly embed forum templates into your application.

**That said**, the presence of `css`/`extra_css`/`js`/`extra_js` blocks does not really encourage that. Perhaps we should opt for new block names (more specific to *django-machina*): `machina_css`, `machina_extra_css`, `machina_js` and `machina_extra_js`. What do you think?

**Comment by Toshakins** [comment]
@ellmetha 

I would like to say thank you for the answer, really appreciate your help.

Actually, our team has `board_base.html` overridden. We want to start with a standard layout offered by **Machina** and then tweak it if needed. As I understood, for overriding purposes one can use `css`/`js` blocks with `super` call. Just found today that demo application shows that approach and I somehow missed it.


About naming. From one side, it is nice to avoid name clashes. Prefixing internal block name with an underscore could also be an option. From the other side, I can't imagine evidence which will lead to issues with the block names. If it would be my personal choice 🤔, I would leave it until some issue on Github with a convincing explanation how does it hurt. However, I think there is a need to update a documentation with a recipe how to apply a custom style(or, maybe, with a point to the demo app for references).

**Comment by Toshakins** [comment]
OK, I consider that my question is fully answered(thanks, by the way). Don't know if any additional action is needed - leaving it's up to maintainer's mind.

Closing the issue.
