### ISSUE TITLE
Support fot django-avatar

### ISSUE THREAD

**Issue by franga2000** [ellmetha/django-machina#67]
I am about to start working on a new, rather large feature, so I'd like to check in with the maintainers first, to make sure my code would be good to merge. To allow for better interoperability with other apps, I would like to add support for [django-avatar](https://github.com/grantmcconnaughey/django-avatar). 

Since a big focus of the project seems to be keeping dependencies to a minimum, I'd like to ask if this is something you'd be interested in merging and if so, what are your requirements:
Should I keep the current avatar system and somehow add this as an option, or would it be ok to replace the current system completely? 

Personally, I think that switching to django-avatar makes the most sense, but if you want the old system to remain, I can do my best to do that.

**Comment by ellmetha** [comment]
Currently the avatar field provided by django-machina is only associated with the forum profile of a user (and not directly to the user itself). The forum profile, which corresponds to the `ForumProfile` model (see [here](https://github.com/ellmetha/django-machina/blob/master/machina/apps/forum_member/abstract_models.py#L17)), is necessary because it embeds some useful values such as posts counts for each user. Sure thing, there is an `avatar` field on this model allowing to set avatars associated with each forum profile, but in real world applications avatars will be generally associated with the `User` model directly. So the `avatar` field provided by the `ForumProfile` is just here to provide basic support for avatars when you're quickly setting up a forum instance.

That said, it is true that the common use case generally involves using an avatar associated with your `User` model directly (eg. with django-avatar). If you're doing this while using django-machina, your only choice will be to override all the templates (and probably some views) displaying the forum users' avatars in order to ensure that the forum pages use the right avatar field.

Perhaps adding support for django-avatar is not necessarily the best thing to do. Instead, we could perhaps add new generic settings and helpers allowing to define where and how avatars should be retrieved / displayed (plus some documentation). Currently django-machina doesn't provide contrib modules (like Django does), but it could also be a solution to add better support for solutions like django-avatar (if applicable). What do you think?

**Comment by franga2000** [comment]
I agree that making the core depend on django-avatar wouldn't be a good idea. I think I might have a way to do it without any breaking changes: 

We create a new template tag (`machina-avatar`?) and modify all the templates to use it. The template tag would look at a setting (`MACHINA_AVATAR_PROVIDER`?) which contained the path (or reference?) to a function (or class?) that would, given a `ForumProfile`, return the URL to the person's avatar.

Machina would have a default implementation of this function, which would use the existing avatar field in `ForumProfile`. If the developer changed the setting to a custom function, machina's avatar field would simply be ignored (and hidden from the admin page with `ForumProfileAdmin.exclude`).

For changing avatars (when using custom providers), I see two ways of handling it.  
Either we simply not show it (by dynamically excluding it from `ForumProfileForm.Meta.fields`), given the fact that almost anyone using a custom avatar system will also have a custom profile update view, or we try to add the provider's update form to `ForumProfileUpdateView` for the (few) users who don't have site-wide profiles and want to use simple providers (like a Gravatar fallback).

**Comment by ellmetha** [comment]
@franga2000 sounds interesting. Feel free to work on this feature and submit a PR if you want!

**Comment by ellmetha** [comment]
Fixed in 89077ff. Thanks @franga2000! 😉
