### ISSUE TITLE
Post._simple_save() method

### ISSUE THREAD

**Issue by dimanjy** [ellmetha/django-machina#71]
Hi!

I'm creating an importer from one php-forum and it works wery slow because of standart Post.save() method. I modified the source of AbstractPost.save():
`
    def save(self, *args, **kwargs):
        new_post = self.pk is None
        super(AbstractPost, self).save(*args, **kwargs)

        # FIXME: Remove after import!
        return

        # Ensures that the subject of the thread corresponds to the one associated
        # with the first post. Do the same with the 'approved' flag.
        if (new_post and self.topic.first_post is None) or self.is_topic_head:
            if self.subject != self.topic.subject or self.approved != self.topic.approved:
                self.topic.subject = self.subject
                self.topic.approved = self.approved

        # Trigger the topic-level trackers update
        self.topic.update_trackers()

`
And it would be great if it will be standart AbstractPost._simple_save() method.

**Comment by ellmetha** [comment]
The standard `Post.save` method triggers tracker updates (eg. posts count in the related topic, etc), which is necessary. This involves updating the topic each time a post is added in it, yes. This behaviour is fine IMHO. If you need to import a lot of posts from another database, you can still write your importation script so that is uses `bulk_create` operations instead of regular inserts (but you'll have to write some additional operations in order to ensure that your model instances remain consistent regarding post counts and similar data). 😉

**Comment by dimanjy** [comment]
I'm updating triggers manually after importing posts. It is around 700K+ posts in my old forum database, so importing with standart Post.save() should take a week.
I decided for myself that dig into docs will be much faster and I wrote my own overriden Post model with _simple_save() method. But I'm worried about the less patient users who will not want to dig into the documentation and because of this they will miss the chance to take advantage of such a wonderful forum software.
